### ISSUE TITLE
uninitialized constant Fog::Errors (NameError)

### ISSUE THREAD

**Issue by helal-ismail** [fog/fog-json#10]
I'm getting this error when running rails s

```
/home/helal/.rvm/gems/ruby-2.1.6/gems/fog-json-1.0.2/lib/fog/json.rb:13:in `<module:JSON>': uninitialized constant Fog::Errors (NameError)
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/fog-json-1.0.2/lib/fog/json.rb:12:in `<module:Fog>'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/fog-json-1.0.2/lib/fog/json.rb:5:in `<top (required)>'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/fog-1.37.0/lib/fog.rb:14:in `<top (required)>'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/asset_sync-1.1.0/lib/asset_sync.rb:1:in `<top (required)>'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
        from /home/helal/work/GIT/fatigue_serverside/config/application.rb:12:in `<top (required)>'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:78:in `require'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/helal/.rvm/gems/ruby-2.1.6/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by icco** [comment]
What's in your Gemfile @helal-ismail? Requiring `fog` is the only way to use fog right now.

**Comment by plribeiro3000** [comment]
Closing due lack of feedback.

Feel free to reopen or comment back if you still have an issue.
